// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.2.0.0
//      Runtime Version:4.0.30128.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace BDD.SpecFlow.Mock.End.Egenskaper.Filmsamling
{
    using TechTalk.SpecFlow;
    
    
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Lista filmer")]
    public partial class ListaFilmerFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Lista_filmer.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("sv"), "Lista filmer", "För att få en överblick av min samling\r\nsom filmsamlare\r\nvill jag kunna lista all" +
                    "a filmer i mitt bibliotek samt se totala antal filmer", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("\"Alien\", \"E.T.\" och \"Jaws\" i filmsamlingen")]
        public virtual void AlienE_T_OchJawsIFilmsamlingen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("\"Alien\", \"E.T.\" och \"Jaws\" i filmsamlingen", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("att filmsamlingen innehåller \"Alien\", \"E.T.\", \"Jaws\"");
#line 9
 testRunner.When("jag anger kommando: ListaFilmer");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Rad"});
            table1.AddRow(new string[] {
                        "Alien"});
            table1.AddRow(new string[] {
                        "E.T."});
            table1.AddRow(new string[] {
                        "Jaws"});
            table1.AddRow(new string[] {
                        "Du har 3 filmer i samlingen"});
#line 10
 testRunner.Then("ska resultatet vara:", ((string)(null)), table1);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
